<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="row-fluid">
				<div class="span8 hero-unit">
					<p>Prezado Aluno aqui nessa pagina você ira se logar com seu
						usuario e senha que foi passado pela secretaria, que é composto
						por 6 dígitos numéricos e a sua senha.</p>
					<p>Ao se autenticar deverá confirmar todos as suas informações
						pessoais, para assim ser produzida a sua carteira estudantil.</p>
					<p>Todos os campos com asterisco (*) são obrigatórios.</p>
					<p>Qualquer duvida entre em contato pelo e-mail: dti@ftec.com.br</p>
				</div>
				<div class="span4 hero-unit">
						<br /><br /><br /><br /><br /><br /><br />
				</div>
			</div>
		</div>
	</div>
</div>

