<br />
<br />
<div class="navbar navbar-inverse">
	<div class="navbar-inner">
	<a class="btn btn-navbar" data-toggle="collapse"
			data-target=".nav-collapse"> <span class="icon-bar"></span> <span
			class="icon-bar"></span> <span class="icon-bar"></span>
		</a>
		<a class="brand" href="/">Carteira Estudante</a>
		<div class="nav-collapse collapse">
			<div class="nav-collapse collapse">
				<ul class="nav">
				<?php if($this->UserIdentity("DTIUser")): ?>
						<li><a href="<?php echo $this->url('dtiuser-admin') ?>"><?php echo 'Painel de Controle' ?></a></li>
					<?php endif; ?>
					<li><a href="/informacaoacesso">Informações de Acesso</a></li>
					<li><a href="/sobre">Sobre</a></li>
					<li><a href="/ajuda">Precisa de Ajuda?</a></li>
				</ul>
			</div>
			<div class="nav-collapse collapse">
				<ul class="nav pull-right">
					<?php if($this->UserIdentity("DTIUser")): ?>
					<li class="nav"><a href="<?php echo $this->url('dtiuser-logout') ?>"><?php echo 'Sair' ?></a></li>
					<?php else: ?>
					<li class="nav"><a href="<?php echo $this->url('dtiuser-auth') ?>"><?php echo 'Entrar' ?></a></li>
					<?php endif; ?>
				</ul>
			</div>
		</div>
	</div>
	<br />

<?php
if($this->UserIdentity("DTIUser")) {
	echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial(array('partials/breadcrumb.phtml',''));
} else {

}

?>
</div>
