<?php echo $this->doctype(); ?>

<html lang="pt">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('FTEC | Faculdades - DTI')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 
        								 'type' => 'image/vnd.microsoft.icon', 
        								 'href' => $this->basePath() . '/img/favicon.ico')) ?>
    
    </head>
    <body>
		
		<!-- HEADER -->
		<div class="container-fluid">
		<?php echo $this->header; ?>
		</div>		
		<!-- CONTENT -->
		<div class="container-fluid">
        <?php echo $this->content; ?>
        </div>
		
		<!-- FOOTER -->
		<div class="container-fluid ">
		<?php echo $this->footer; ?>
		</div>
		<!-- JS -->
		<?php echo $this->inlineScript() ?>

    </body>
</html>